import {
    Calculator,
    Building2,
    Building,
    Briefcase,
    HandshakeIcon,
    Code2,
    Zap,
    Wrench,
    Paintbrush2,
    HardHat,
    LandPlot,
    HeartPulse,
    UtensilsCrossed,
    TrendingUp,
    ShieldCheck,
    Map,
    Trees,
    Scale,
    Wallet,
    Megaphone,
    Factory,
    Key,
    Gem,
    UserRound,
    MonitorSmartphone,
    Newspaper,
    Home,
    Lock,
    Truck,
    HelpCircle,
    DraftingCompass,
    Landmark,
    Construction,
    Armchair,
    ChartNoAxesCombined,
    BrickWall
} from "lucide-react";

export const PERSONA_OPTIONS = [
    { value: 'Accountant', icon: Calculator },
    { value: 'Architect', icon: DraftingCompass },
    { value: 'Banker', icon: Landmark },
    { value: 'Consultant', icon: Briefcase },
    { value: 'CRE Broker', icon: HandshakeIcon },
    { value: 'Developer', icon: Construction },
    { value: 'Electrician', icon: Zap },
    { value: 'Engineer', icon: Wrench },
    { value: 'Interior Designer', icon: Armchair },
    { value: 'General Contractor', icon: HardHat },
    { value: 'Government', icon: LandPlot },
    { value: 'Healthcare', icon: HeartPulse },
    { value: 'Hospitality / Restaurants', icon: UtensilsCrossed },
    { value: 'Institutional Investor', icon: ChartNoAxesCombined },
    { value: 'Insurance / Underwriter', icon: ShieldCheck },
    { value: 'Land Use Consultant / Expeditor', icon: Map },
    { value: 'Landscape Design / Architect', icon: Trees },
    { value: 'Law Firm / Legal Services', icon: Scale },
    { value: 'Lender', icon: Wallet },
    { value: 'Marketing / PR', icon: Megaphone },
    { value: 'Materials', icon: BrickWall },
    { value: 'Owner / Investor', icon: Key },
    { value: 'Private Equity', icon: Gem },
    { value: 'Professional Services', icon: UserRound },
    { value: 'Property Management', icon: Building },
    { value: 'PropTech', icon: MonitorSmartphone },
    { value: 'Publishing / Media', icon: Newspaper },
    { value: 'Real Estate Investment Firm', icon: Home },
    { value: 'Real Estate Investment Trust (REIT)', icon: Building2 },
    { value: 'Security Company', icon: Lock },
    { value: 'Transportation / Logistics / Storage', icon: Truck },
    { value: 'Other', icon: HelpCircle }
] as const;

export type PersonaOption = typeof PERSONA_OPTIONS[number];
export type PersonaValue = PersonaOption['value']; 